ABC: add missing chain_context arg to VirtualMachineAPI's constructor.
This silences `mypy` error:

    eth/chains/base.py:250: error: Unexpected keyword argument "chain_context" for "VirtualMachineAPI"
    eth/abc.py:2270: note: "VirtualMachineAPI" defined here

This change has been copy-pasted from the previous PR.
I would've cherry-picked it in, but since then the constructor
has changed, adding in `consensus_context`, too.

Anyway, here's the previous PR's commit:

https://github.com/ethereum/py-evm/pull/1885/commits/97cc8db2cb52d9221cb5d8ca2b5ff238391132ca