setup: update to package versions that have Python 3.8 wheels.
Minimal set of dependencies that otherwise break the virtualenv,
detailed here:

https://github.com/ethereum/py-evm/issues/1872#issuecomment-559114127

SQUASHED:

setup: bump `plyvel` version so pre-built wheel can be used:

https://github.com/ethereum/py-evm/issues/1872#issuecomment-559144359

setup: bump minimum eth-utils to v1.8.0 (has Python 3.8 support).

v1.9.0 is installed now anyway, but this has been suggested in

https://github.com/ethereum/py-evm/pull/1885#issuecomment-562208075

setup: bump `pyflake` nested dependency to that with Python 3.8 support.

Get around:

    AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

`pyflakes` has proper support from v2.2.0, which in turn was added to
`flake8` as a dependency in the v3.8.x branch:

    https://gitlab.com/pycqa/flake8/-/blob/3.8.0/setup.cfg

Also bump `flake8-bugbear` to latest version while we're at it,
even though its dependency on `flake8` is rather lax:

    https://github.com/PyCQA/flake8-bugbear/blob/20.1.4/setup.py#L41