eth/vm/state: expect Hash32 (not bytes) in __init__ of BaseState.
Again, 99.99% cargo-culting. This just silences a `mypy` error:

    eth/vm/state.py:57: error: Argument 2 to "AccountDatabaseAPI" has incompatible type "bytes"; expected "Hash32"

A valid state root will definitely be a 32-byte-long hash. Question
is if this is the right place to make sure of it; and whether that
should be made more explicit in code than being picky about a type.

This commit has been cherry-picked from previous PR:

https://github.com/ethereum/py-evm/pull/1885/commits/851c141d18f9b47261ef45f47e27d5fb90d2e63c